# syntax=docker/dockerfile:1

# ---- Base ----
# Next.js 16 requires Node.js 20.9+; use the current Alpine LTS image.
FROM node:22-alpine AS base

# ---- Dependencies ----
# Install dependencies only when lockfile changes for better layer caching.
FROM base AS deps
# libc6-compat helps some native deps run on Alpine.
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ---- Builder ----
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ---- Runner ----
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Run as a non-root user.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# Copy public assets.
COPY --from=builder /app/public ./public

# Copy the standalone output (includes a minimal node_modules and server.js).
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy the static assets generated by `next build`.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is created by the standalone output.
CMD ["node", "server.js"]
